spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/demo
spring.datasource.username=postgres
spring.datasource.password=938326

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
